import { body } from 'express-validator';

export const validateAssistantAdmin = [
    body('photo').optional().notEmpty().withMessage('Photo is required.'),
    body('name').optional().notEmpty().withMessage('Name is required.'),
    body('empId').optional().notEmpty().withMessage('Employee ID is required.'),
    body('email').optional().isEmail().withMessage('Valid email is required.'),
    body('phoneNumber').optional().notEmpty().withMessage('Phone number is required.'),
    body('whatsappNumber').optional().isString(),
    body('dateOfBirth').optional().isDate().withMessage('Date of birth is required.'),
    body('qualification').optional().notEmpty().withMessage('Qualification is required.'),
    body('place').optional().notEmpty().withMessage('Place is required.'),
    body('pincode').optional().notEmpty().withMessage('Pincode is required.'),
    body('address').optional().notEmpty().withMessage('Address is required.'),
    body('timezone').optional().notEmpty().withMessage('Timezone is required.'),
    body('previousCompanies').optional().isArray(),
    body('preferredLanguage').optional().notEmpty().withMessage('Preferred language is required.'),
    body('resumeLink').optional().isURL().withMessage('Resume link must be a valid URL.'),
    body('upiId').optional().isString(),
    body('accountNumber').optional().isString(),
    body('accountHolderName').optional().isString(),
    body('accountType').optional().isString(),
    body('ifscCode').optional().isString(),
    body('bankName').optional().isString(),
];
